allow_login_shell = true
approval_policy = "never"
sandbox_mode = "danger-full-access"
web_search = "live"

[mcp_servers.context7]
args = [
    "-y",
    "@upstash/context7-mcp@latest",
]
command = "npx"

[mcp_servers.playwright]
args = [
    "-y",
    "@playwright/mcp@latest",
]
command = "npx"
